### ISSUE TITLE
终于等到有用一样主板了的😅

### ISSUE THREAD

**Issue by yizhiheng** [intihyan/OC-b460i-strix-i7-10700#1]
请问一下你完整度怎么样呀? 我跟你的配置一样, 我现在用的CPU伪装, 基本可以用..有些程序打开会闪退比如Intel power gadget

还有你是OC 0.6.0吗?

**Comment by intihyan** [comment]
对是0.6.0. 如果是一样的板子的话感觉应该可以直接替换。 Intel power gadget我试过了在我这是好的，是不是因为你是用的集显我用的是独显？

基本上是完美的，声卡不识别和USB3.0变2.0的问题是参考了这篇帖子https://post.smzdm.com/p/ag89g4z7/

**Comment by yizhiheng** [comment]
好的感谢, 我周末试试!
