### ISSUE TITLE
Need help on Asus B460i and RX 5500 XT with OpenCore 0.6

### ISSUE THREAD

**Issue by lambertlu** [intihyan/OC-b460i-strix-i7-10700#2]
Hi There,

This is my first build, thanks for the help.My hardware list:

> - Asus ROG STRIX B460-I GAMING (I swapped the Intel® Wi-Fi 6 AX200 with a DW1820A, tested working in Windows 10.)
> - ASUS AMD Radeon RX 5500XT Overclocked O8G GDDR6 Dual Fan EVO Edition
> - WD_BLACK SN750 NVMe SSD 500GB
> - G.SKILL Ripjaws DDR4 3200MHz 32GB(16GBx2)

Made a macOS Catalina 10.15.6 USB with OpenCore 0.6 from Apple Store, followed the guide:Making the installer in macOS | OpenCore Install GuideMy start point: https://github.com/intihyan/OC-b460i-strix-i7-10700This Repo seems to use the same motherboard.Followed: Desktop Comet Lake updates the [config.plist] by ProperTree.

I choice iMac19,1 in GenSMBIOS.Connect my monitor via the RX 5500XT, is that the right way? Please let me know.

BIOS setting:
Disable

- > Fast Boot
- > Secure Boot
- > Serial/COM Port
- > Parallel Port
- > VT-d
- > CSM
- > Intel SGX
- > Intel Platform Trust
- > CFG / CFG-Lock distable c-states (Advanced\CPU Config\CPU - Power Management Controll)

Enable

- > VT-x
- > Above 4G decoding / Above 4G assignment
- > Hyper-Threading
- > EHCI/XHCI Hand-off
- > DVMT Pre-Allocated(iGPU Memory): 64MB
- > OS type: Other OS ( I have to do this, OpenCore USB will not boot if I select the Windows UEFI option. Guess this is the [Secure Boot disable] )
- > SATA Mode: AHCI

Attached please find my OpenCore debug log file, config.plist and the whole EFI folder.

https://www.dropbox.com/sh/yqb2tkzaxwez9ze/AAD5dRyGqy3pQ0Zn2xvTQHw1a?dl=0

hung on boot, the few lines are:

`IOUSBHostInterface(0x10000032c): matching deferred by IOUSBHostHIDDevice

Previous shutdown cause: 5

IOUSBHostInterface(0x10000032c): matching deferred by IOUSBHostHIDDevice
`

**Comment by intihyan** [comment]
I think this might be the same problem I have experienced.

You might need to get a USB-C to USB A hub, and connect your USB drive through that hub.  It seems to me the only working USB port once you boot into OpenCore, is that USB-C port.

**Comment by lambertlu** [comment]
Thank you so much for the tips.
I am able to boot into install GUI by using a USB-C hub.

**Comment by lambertlu** [comment]
I installed the macOS to the hard disk.
Have a few issues:
1. My RX 5500 XT fans not spinning, even under heavy load. And it became very hot.
2. No Bluetooth with my DW1280A.

How's your 5600 XT Fan works?

**Comment by intihyan** [comment]
In terms of the RX 5500XT,  mine is the MSI branded although I don't think too much of a difference, but anyhow I don't have to tweak anything and its working perfectly.   MacOS Catalina is supposed to support it out of the box.  Are you sure the fan is spinning when in Windows? In other words, make sure its not a hardware issue. 

As for the Bluetooth one, I can't tell you what's wrong because in my case the DW1560 is working for both WiFi and Bluetooth only by placing the AirportBrcm kext.  Perhaps you can google similar issue, like this one https://www.youtube.com/watch?v=KttwKmIwOBU

**Comment by lambertlu** [comment]
Thanks a lot for your kind help.
The Asus RX 5500XT works fine in Windows, and the fan spins.

I will try the youtube method today.

**Comment by solaris256** [comment]
I also encountered the same problem before，thank for your help to  solved problem
